version: "2"
services:
  appdb:
    container_name: "database"
    image: mysql:5.5
    network_mode: "maxor-net"
    environment:
      - "constraint:node==swarm-node-01"
      - MYSQL_ROOT_PASSWORD=qwerty123
      - MYSQL_DATABASE=gojidb
      - MYSQL_USER=goji
      - MYSQL_PASSWORD=goji123
  webapp:
    container_name: "webapp"
    image: maxor/goji_webapp
    network_mode: "maxor-net"
    environment:
      - "constraint:node==swarm-node-02"
    depends_on:
      - appdb
    ports:
      - 8000:8000
    links:
      - appdb
