[general]
public_path   = "public"
template_path = "views"

[cookie]
mac_secret = "secret string which has over 256-bit entropy"
secure     = false

[database]
user     = "goji"
password = "goji123"
hostname = "appdb"
port     = "3306"
database = "gojidb"

[csrf]
key    = "csrf_token"
cookie = "XSRF-TOKEN"
header = "X-XSRF-TOKEN"
